# Generated by Django 5.0 on 2024-01-02 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=8)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(choices=[(-1, 'Did not like the course'), (0, 'Neutral'), (1, 'Liked the course')], help_text="1 if the student enjoyed the course, -1 if the student didn't enjoy the course, 0 if they were neutral.")),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.experience')),
            ],
        ),
    ]
