# Generated by Django 5.0 on 2024-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='creation_date',
            field=models.DateField(auto_now=True),
        ),
    ]
