# Generated by Django 5.0 on 2024-01-03 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_comment_creation_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='rating',
            new_name='rating_old',
        ),
    ]
