# Generated by Django 5.0 on 2024-01-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_rating_experience_rating_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(choices=[(-1, 'Did not like the course'), (0, 'Neutral'), (1, 'Liked the course')], default=1, help_text="2 if the student enjoyed the course, 1 if the student didn't enjoy the course, 0 if they were neutral."),
        ),
    ]
