# Generated by Django 5.0 on 2024-01-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_experience_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='rating_old',
        ),
        migrations.AlterField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(choices=[(2, 'Did not like the course'), (1, 'Neutral'), (0, 'Liked the course')], default=1, help_text="2 if the student enjoyed the course, 1 if the student didn't enjoy the course, 0 if they were neutral."),
        ),
    ]
