# Generated by Django 5.0 on 2024-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_experience_rating_old_alter_experience_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(choices=[(0, 'Did not like the course'), (1, 'Neutral'), (2, 'Liked the course')], default=1, help_text="2 if the student liked the course, 1 if the student didn't like the course, 0 if they were neutral."),
        ),
    ]
